#!/bin/bash

if [ $# -ne 2 ]
then
echo "Wrong number of parameters entered. Plese enter a folder name and a file name"
else
if [ ! -d "~/folders/$1" ]
then
mkdir ~/folders/$1
fi
cd ~/folders/$1
echo "Hello" >> $2.txt
fi
